"""
AREA OF CIRCLE
AREA OF TRIANGLE
AREA OF SQUARE
AREA OF RECTANGLE
CONVERTING CM TO METRES
CONVERTING METRES TO KM
CONVERTING KM TO MILES
VOLUME OF A CUBE
VOLUME OF A CYLINDER
VOLUME OF A SPHERE
VOLUME OF A PYRAMID
"""